// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJZq_7r1tEVSgbPNGCQLh53IBtdRi3d5Q',
    appId: '1:331199458552:android:19272c388ee2a03f4d5f0d',
    messagingSenderId: '331199458552',
    projectId: 'amora-6a0e1',
    storageBucket: 'amora-6a0e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2-x1-0dAnFcQ264F9WWv3oTQlCwDDS0k',
    appId: '1:331199458552:ios:1696e44b0c8b71c74d5f0d',
    messagingSenderId: '331199458552',
    projectId: 'amora-6a0e1',
    storageBucket: 'amora-6a0e1.appspot.com',
    androidClientId: '331199458552-75216t81j7bhlgh2ten0nasigb3b3mpd.apps.googleusercontent.com',
    iosClientId: '331199458552-4dbt7o0bdrcajrk1rjk856u1h1egaf2i.apps.googleusercontent.com',
    iosBundleId: 'com.example.amoraMobileApp',
  );

}